spring.application.name=enterprise-payment-api

server.port=${PORT:8080}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/paymentdb}
spring.datasource.username=${DB_USERNAME:paymentuser}
spring.datasource.password=${DB_PASSWORD:paymentpass}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=${SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false